### ISSUE TITLE
403 error while deploying using GitHub actions

### ISSUE THREAD

**Issue by Evertt** [babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template#14]
So I simply used your repo as a template and then I followed all the instructions to get it to work with my Firebase project. It all seemed to go well until I pushed my commit and the GitHub actions gave me the following error:

```
Run npm run firebase:deploy:functions

> sapper-firebase-typescript-graphql-tailwindcss-actions-template@2020.8.20 firebase:deploy:functions /home/runner/work/sapper-cms/sapper-cms
> firebase deploy --only functions

⚠  functions: package.json indicates an outdated version of firebase-functions.
Please upgrade using npm install --save firebase-functions@latest in your functions directory.

=== Deploying to 'mytryout-246d2'...

i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
⚠  functions: missing required API cloudbuild.googleapis.com. Enabling now...
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing . directory for uploading...
i  functions: packaged . (1.52 MB) for uploading
⚠  functions: Upload Error: HTTP Error: 403, Unknown Error

Error: HTTP Error: 403, Unknown Error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sapper-firebase-typescript-graphql-tailwindcss-actions-template@2020.8.20 firebase:deploy:functions: `firebase deploy --only functions`
npm ERR! Exit status 1
npm ERR! 
```

I haven't got the slightest clue what exactly is throwing this 403 error and why. As far as I'm aware I did exactly what was needed to set everything up correctly. Do you have any idea?

**Comment by babichjacob** [comment]
I've just gotten the same error on a new project.

**Comment by Evertt** [comment]
@babichjacob never mind, the fix was too simple. I just had to go to the functions page in my firebase console and click "Get started..."

**Comment by babichjacob** [comment]
Try running (p)`npm update` and running `deploy` again.

**Comment by Evertt** [comment]
@babichjacob were you able to get it to work using the tip that I gave in my comment above yours?

> @babichjacob never mind, the fix was too simple. I just had to go to the functions page in my firebase console and click "Get started..."

**Comment by babichjacob** [comment]
I don't remember doing that when I set up the project a couple days ago

**Comment by Evertt** [comment]
> I don't remember doing that when I set up the project a couple days ago

What do you mean? You don't remember clicking the **"Get started"** button, but it works now? Does it work now for you?

Because what I'm saying is, if it's *not* working for you then maybe you forgot to click the **"Get started"** button on the functions page in the firebase console.

![image](https://user-images.githubusercontent.com/1267282/91307642-86327180-e7ae-11ea-8329-5e7479dd6594.png)

![image](https://user-images.githubusercontent.com/1267282/91307751-a6623080-e7ae-11ea-9af5-1c82d5e217a3.png)

**Comment by babichjacob** [comment]
> > I don't remember doing that when I set up the project a couple days ago
> 
> What do you mean? You don't remember clicking the **"Get started"** button, but it works now? Does it work now for you?

I believe I only did the Firebase project creation that dropped me in the console page but didn't click anything else. Yes, it works now either after a second attempt at deploying or because I updated dependencies with `npm update` (or both), but I don't know which.

**Comment by Evertt** [comment]
Well I didn't do `npm update` so that definitely wasn't it.

**Comment by saurabhshah23** [comment]
> @babichjacob never mind, the fix was too simple. I just had to go to the functions page in my firebase console and click "Get started..."

I would have never guessed this. Thanks.
