### ISSUE TITLE
I also just wanted to say thank you

### ISSUE THREAD

**Issue by Evertt** [babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template#17]
As far as I'm aware there's no way to send people messages on github except through issues or pull requests, so that's why I'm writing this in an issue.

I just wanted to say that I deeply appreciate all the work you've done on this template. I was working on my own template with all the exact same features that you've implemented, but mine was still far from finished, because it takes a lot of time to get everything to work together just right.

So thank you for putting in that time and I'm really enjoying how well you've actually put it together. I don't think I could've done it this good.

🙏🙏🙏

**Comment by babichjacob** [comment]
No problem.

**Comment by GGAlanSmithee** [comment]
Thanks a bunch for this boilerplate @babichjacob
