### ISSUE TITLE
Just a question, have you been able to get GraphQL subscriptions to work connected to Firestore subscriptions? On a per-user-session basis?

### ISSUE THREAD

**Issue by Evertt** [babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template#20]
So the main reason I was initially not interested in the GraphQL part of this template, is just because of how much I love the ease of subscribing to snapshots from Firestore queries in the browser. And I didn't think that that would  be very easy to do if I would need to use GraphQL as a middleman. Especially not when those Firestore queries are based on which user is logged in.

However, not that I've run into some annoying limitations of Firestore in the browser, for example that you can't use an `offset()` in a query, even though that is definitely possible in `firebase-admin`, I'm starting to get curious if GraphQL could make life a little better for me.

But honestly, I would *only* be interested in using GraphQL if it's possible to use GraphQL subscriptions, which under the hood would just subscribe to Firestore connections, and if it's possible to have those subscriptions scoped to the currently authenticated user (if there is any).

So I'm just wondering, did you ever get that to work?

**Comment by babichjacob** [comment]
I've never tried

**Comment by Evertt** [comment]
Ah, that's too bad. I might give it a shot and then I'll let you know how that went.
