### ISSUE TITLE
Add SCSS support

### ISSUE THREAD

**Issue by multipliedtwice** [babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template#24]
Greetings, nice package. How do I add scss support to it?

**Comment by babichjacob** [comment]
👋 Hi! Unfortunately, I don't know how to use SCSS so I've never tried it before 😦.

**Comment by babichjacob** [comment]
Sapper's remaining lifespan is too short for me to want to add new features to this project. Sorry.
