### ISSUE TITLE
Replace tailwindcss with windicss?

### ISSUE THREAD

**Issue by Evertt** [babichjacob/sapper-firebase-typescript-graphql-tailwindcss-actions-template#27]
Since it's a better / faster compiler that produces the same result, but has even a few more features.

I've been trying to do it in my fork of this template, but I can't completely do away with postcss, since I also use it for things like `postcssNested`. And right now I can't get both to work. I wonder if you'd know a way to include both and if you think it's worth it to migrate this template to windicss.

**Comment by babichjacob** [comment]
Sapper's lifespan is too short for me to be interested.

**Comment by Evertt** [comment]
Okay :-)

**Comment by babichjacob** [comment]
Wrote more in #28
